const LOAD_ORDER_LIST_TO_LOCAL = 'seeOrder/LOAD_ORDER_LIST_TO_LOCAL';   // 把从服务器接收到的订单列表加载到本地
const SELECTED_ARRIVED_FALSE = 'seeOrder/SELECTED_ARRIVED_FALSE';   // 选中"待派送"
const SELECTED_ARRIVED_TRUE = 'seeOrder/SELECTED_ARRIVED_TRUE';   // 选中"待派送"

export {
    LOAD_ORDER_LIST_TO_LOCAL,
    SELECTED_ARRIVED_FALSE,
    SELECTED_ARRIVED_TRUE
};